/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plukodgyakorlo2;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Verosffy
 */
public class Adatkikerdezo extends javax.swing.JFrame {

    ArrayList<TermekKodParos> termekek = new ArrayList<TermekKodParos>();
    TermekKodParos kivalasztottTermekkodparos;
    int tippindex;
    int kerdesekSzama=0;
    int joValaszokSzama=0;
    int teljesListameret;
    String info;

    public Adatkikerdezo() {
        initComponents();
        listafeltolto();
        teljesListameret=termekek.size();
        termekkodField.setText("");
        kerdeskor();
        
        
        

    }
    public void kerdeskor(){
        kerdesekSzama++;
        info=kerdesekSzama+". kérdés,"+joValaszokSzama+"/"+teljesListameret;
        rekordField.setText(info);
        tippKodField.setText("");
        termekkodField.setText("");
        System.out.println(termekek.size());
        sorszamkivaszto();
        System.out.println("tippindex= "+tippindex);
        if (tippindex==-1){
            termeknevField.setText("grat , már mindent tudsz.");
        }else{
        kivalasztottTermekkodparos = termekek.get(tippindex);

        termeknevField.setText("" + kivalasztottTermekkodparos.getTermeknev());
    }
    }
    public void listafeltolto() {
        try {
            FileInputStream file = new FileInputStream("src\\segedlet\\TermekKodparos.dat");
            ObjectInputStream inputObject = new ObjectInputStream(file);

            boolean tartmegafile = true;
            while(tartmegafile)
            try {
                
                    termekek.add((TermekKodParos) inputObject.readObject());
                

            } catch (EOFException e) {
                tartmegafile = false;
            }
            inputObject.close();
        } catch (IOException ex) {
            Logger.getLogger(Adatkikerdezo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Adatkikerdezo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public int sorszamkivaszto() {

        int letszam = termekek.size();
        if(letszam==0) return -1;
        else{
        
        Random rd = new Random();

        tippindex= rd.nextInt(letszam);
        return tippindex;}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        termeknevField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tippKodField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        termekkodField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        rekordField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Terméknév:");

        termeknevField.setText("jTextField1");
        termeknevField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termeknevFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("kod tipp:");

        tippKodField.setText("jTextField1");
        tippKodField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tippKodFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("kod helyesen:");

        termekkodField.setText("jTextField1");

        jLabel4.setText("jelenlegi rekord:");

        rekordField.setText("jTextField1");

        jButton1.setText("kövi kérdés");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rekordField, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(termekkodField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tippKodField, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(termeknevField, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(termeknevField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tippKodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(termekkodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(rekordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void termeknevFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termeknevFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_termeknevFieldActionPerformed

    private void tippKodFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tippKodFieldActionPerformed
        String kodtipp = tippKodField.getText();
        if (kodtipp.equalsIgnoreCase(kivalasztottTermekkodparos.getTermekkod())) {
            termekkodField.setText("Helyes!");
            joValaszokSzama++;
            
            termekek.remove(kivalasztottTermekkodparos);
        }else{
            termekkodField.setText(kivalasztottTermekkodparos.getTermekkod());
        }
        
        

    }//GEN-LAST:event_tippKodFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        kerdeskor();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adatkikerdezo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adatkikerdezo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adatkikerdezo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adatkikerdezo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adatkikerdezo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField rekordField;
    private javax.swing.JTextField termekkodField;
    private javax.swing.JTextField termeknevField;
    private javax.swing.JTextField tippKodField;
    // End of variables declaration//GEN-END:variables
}
