/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plukodgyakorlo2;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Verosffy
 */
public class TermekTorlese extends javax.swing.JFrame {

    /**
     * Creates new form TermekTorlese
     */
    int kivalasztottElemIndexe;
    ArrayList<TermekKodParos> termekek = new ArrayList<>();
    String[] termekNevek;
    String[] termekKodok;

    public TermekTorlese() {
        initComponents();
        jTFTorlesreKivalsztottTermekKod.setText("                ");
        jTFTorlesreKivalsztottTermekNev.setText("");
        populateArrayList();
        termeknevekFeltolto();
        termekKodokFeltolto();
    }

    public void termeknevekFeltolto() {
        termekNevek = new String[termekek.size()];
        for (int i = 0; i < termekek.size(); i++) {
            termekNevek[i] = termekek.get(i).getTermeknev();
        }
        jCBTermekNevek.setModel(new javax.swing.DefaultComboBoxModel<>(termekNevek));
    }

    public void termekKodokFeltolto() {
        termekKodok = new String[termekek.size()];
        for (int i = 0; i < termekek.size(); i++) {
            termekKodok[i] = termekek.get(i).getTermekkod();

        }
        jCBTermekKodok.setModel(new javax.swing.DefaultComboBoxModel<>(termekKodok));
    }

    public void saveToFile() {
        try {
            FileOutputStream file = new FileOutputStream("src\\segedlet\\TermekKodparos.dat");
            ObjectOutputStream kimenoObject = new ObjectOutputStream(file);
            for (int i = 0; i < termekek.size(); i++) {
                kimenoObject.writeObject(termekek.get(i));

            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TermekTorlese.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TermekTorlese.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void populateArrayList() {
        try {
            FileInputStream file = new FileInputStream("src\\segedlet\\TermekKodparos.dat");
            ObjectInputStream inputObject = new ObjectInputStream(file);

            boolean vegevanafilenak = false;
            while (!vegevanafilenak) {
                try {
                    termekek.add((TermekKodParos) inputObject.readObject());
                } catch (EOFException e) {
                    vegevanafilenak = !vegevanafilenak;
                } catch (Exception ex) {
                    Logger.getLogger(TermekTorlese.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            inputObject.close();

        } catch (IOException ex) {
            Logger.getLogger(TermekTorlese.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCBTermekNevek = new javax.swing.JComboBox<>();
        jCBTermekKodok = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTFTorlesreKivalsztottTermekNev = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTFTorlesreKivalsztottTermekKod = new javax.swing.JTextField();
        jBTorles = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jBTorolniSzeretnem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCBTermekNevek.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCBTermekNevek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBTermekNevek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTermekNevekActionPerformed(evt);
            }
        });

        jCBTermekKodok.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jCBTermekKodok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCBTermekKodok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBTermekKodokActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Törlésre kiválasztott termék neve:");

        jTFTorlesreKivalsztottTermekNev.setEditable(false);
        jTFTorlesreKivalsztottTermekNev.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTFTorlesreKivalsztottTermekNev.setText("jTextField3");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Kiválasztás név alapján:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Kiválasztás kód alapján");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Törlésre kiválasztott termék kódja");

        jTFTorlesreKivalsztottTermekKod.setEditable(false);
        jTFTorlesreKivalsztottTermekKod.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTFTorlesreKivalsztottTermekKod.setText("jTextField1");
        jTFTorlesreKivalsztottTermekKod.setPreferredSize(new java.awt.Dimension(150, 20));

        jBTorles.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBTorles.setText("Törlés");
        jBTorles.setEnabled(false);
        jBTorles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTorlesActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Vissza");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jBTorolniSzeretnem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jBTorolniSzeretnem.setText("Törölni szeretném");
        jBTorolniSzeretnem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTorolniSzeretnemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jBTorolniSzeretnem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                .addComponent(jBTorles)
                .addGap(288, 288, 288))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jCBTermekNevek, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jCBTermekKodok, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jTFTorlesreKivalsztottTermekKod, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTFTorlesreKivalsztottTermekNev)))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCBTermekNevek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCBTermekKodok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTFTorlesreKivalsztottTermekNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFTorlesreKivalsztottTermekKod, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTorolniSzeretnem)
                    .addComponent(jBTorles))
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBTermekNevekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTermekNevekActionPerformed
        kivalasztottElemIndexe = jCBTermekNevek.getSelectedIndex();
        jTFTorlesreKivalsztottTermekNev.setText(termekek.get(kivalasztottElemIndexe).getTermeknev());
        jTFTorlesreKivalsztottTermekKod.setText(termekek.get(kivalasztottElemIndexe).getTermekkod());
    }//GEN-LAST:event_jCBTermekNevekActionPerformed

    private void jCBTermekKodokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBTermekKodokActionPerformed
        kivalasztottElemIndexe = jCBTermekKodok.getSelectedIndex();
        jTFTorlesreKivalsztottTermekNev.setText(termekek.get(kivalasztottElemIndexe).getTermeknev());
        jTFTorlesreKivalsztottTermekKod.setText(termekek.get(kivalasztottElemIndexe).getTermekkod());
    }//GEN-LAST:event_jCBTermekKodokActionPerformed

    private void jBTorolniSzeretnemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTorolniSzeretnemActionPerformed
        if (!jTFTorlesreKivalsztottTermekNev.getText().equalsIgnoreCase("")) {
            jBTorles.setEnabled(true);
        }
    }//GEN-LAST:event_jBTorolniSzeretnemActionPerformed

    private void jBTorlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTorlesActionPerformed
        termekek.remove(termekek.get(kivalasztottElemIndexe));
        saveToFile();
        jTFTorlesreKivalsztottTermekKod.setText("");
        jTFTorlesreKivalsztottTermekNev.setText("");
        populateArrayList();
        termeknevekFeltolto();
        termekKodokFeltolto();
    }//GEN-LAST:event_jBTorlesActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TermekTorlese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TermekTorlese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TermekTorlese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TermekTorlese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TermekTorlese().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBTorles;
    private javax.swing.JButton jBTorolniSzeretnem;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jCBTermekKodok;
    private javax.swing.JComboBox<String> jCBTermekNevek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTFTorlesreKivalsztottTermekKod;
    private javax.swing.JTextField jTFTorlesreKivalsztottTermekNev;
    // End of variables declaration//GEN-END:variables
}
