/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plukodgyakorlo2;

import java.io.EOFException;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Verosffy
 */
public class TesztInditas extends javax.swing.JFrame {

    ArrayList<TermekKodParos> termekek;
    ArrayList<TermekKodParos> termekekTesztre;
    int hossz;
    String egytermeknev;
    String egytermekkod;
    int kerdesekSzama = 0;
    int helyesValaszokSzama = 0;
    int egymasutanjo = 0;
    int tesztekszama = 1;
    int szazalek;
    int sz80tolSz = 0;
    int sz90tolSz = 0;
    int sz100Sz = 0;
    int sz70tolSz = 0;

    /**
     * Creates new form TesztInditas
     */
    public void szazalekszamitas() {
        if (kerdesekSzama == 0) {
            szazalek = 0;
        } else {
            szazalek = (100 * helyesValaszokSzama) / kerdesekSzama;
        }
    }

    public TesztInditas() {

        initComponents();
        sz80tol.setText("" + sz80tolSz);
        sz90tol.setText("" + sz90tolSz);
        sz100.setText("" + sz100Sz);
        sz70tol.setText("" + sz70tolSz);

        termekekTesztre = new ArrayList<TermekKodParos>();
        termekek = new ArrayList<TermekKodParos>();
        feltoltes();
        tesztrefeltoltes();
        tesztekszamaField.setText("" + tesztekszama);
        egymasUtanJoField.setText("" + egymasutanjo);
    }

    public void tesztrefeltoltes() {
        for (int i = 0; i < 10; i++) {
            randomtermek(termekek);
            TermekKodParos uj = new TermekKodParos(egytermeknev, egytermekkod);
            termekekTesztre.add(uj);
        }
    }

    public void feltoltes() {
        try {
            FileInputStream file = new FileInputStream("src\\segedlet\\TermekKodparos.dat");
            ObjectInputStream inputObject = new ObjectInputStream(file);

            boolean endOfFile = false;
            while (!endOfFile) {
                termekek.add((TermekKodParos) inputObject.readObject());
            }
        } catch (EOFException e) {

        } catch (IOException e) {

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(TesztInditas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void randomtermek(ArrayList<TermekKodParos> lista) {

        Random rd = new Random();
        hossz = lista.size();
        int n = rd.nextInt(hossz);
        egytermekkod = lista.get(n).getTermekkod();
        egytermeknev = lista.get(n).getTermeknev();

    }
    public void kodkiiras(){
        String helyeskod=""+egytermekkod;
        String tipp=tippField.getText();
        if(tipp.equalsIgnoreCase(helyeskod)){
            helyesKodField.setText("Helyes!");
        }else{
            helyesKodField.setText(helyeskod);
        }
    }

    public void kodellenorzes() {
        String helyeskod = "" + egytermekkod;
        String tipp = tippField.getText();
        kerdesekSzama++;
        if (tipp.equalsIgnoreCase(helyeskod)) {
            helyesValaszokSzama++;
            egymasutanjo++;

            helyesKodField.setText("Helyes!");
        } else {
            egymasutanjo = 0;
            helyesKodField.setText(helyeskod);
        }
        int szazalek = (100 * helyesValaszokSzama) / kerdesekSzama;
        szazalekField.setText("" + szazalek);
        egymasUtanJoField.setText("" + egymasutanjo);
    }

    public void ujlistkeszito() {
        if (szazalek == 100) {
            sz100Sz++;
            sz100.setText("" + sz100Sz);
        } else if (szazalek >= 90) {
            sz90tolSz++;
            sz90tol.setText("" + sz90tolSz);
        } else if (szazalek >= 80) {
            sz80tolSz++;
            sz80tol.setText("" + sz80tolSz);
        } else if (szazalek >= 70) {
            sz70tolSz++;
            sz70tol.setText("" + sz70tolSz);
        }

        egymasutanjo = 0;
        egymasUtanJoField.setText("" + egymasutanjo);
        tesztekszama++;
        tesztekszamaField.setText("" + tesztekszama);

        tippField.setText("");
        termeknevField.setText("");
        tesztrefeltoltes();
        randomtermek(termekekTesztre);
        termeknevField.setText(egytermeknev);
        helyesValaszokSzama = 0;
        kerdesekSzama = 0;
        szazalekField.setText("0");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        termeknevField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tippField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        helyesKodField = new javax.swing.JTextField();
        mehetButton = new javax.swing.JButton();
        kovKerdesButton = new javax.swing.JButton();
        befejezemButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        szazalekField = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        ujListakeroGomb = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        egymasUtanJoField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tesztekszamaField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sz80tol = new javax.swing.JTextField();
        sz90tol = new javax.swing.JTextField();
        sz100 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        sz70tol = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Termék neve:");

        termeknevField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termeknevFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("tipp");

        tippField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tippFieldActionPerformed(evt);
            }
        });
        tippField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tippFieldKeyPressed(evt);
            }
        });

        jLabel3.setText("Helyes megoldás:");

        mehetButton.setText("Mehet");
        mehetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mehetButtonActionPerformed(evt);
            }
        });

        kovKerdesButton.setText("Tovább");
        kovKerdesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kovKerdesButtonActionPerformed(evt);
            }
        });

        befejezemButton.setText("Befejezem");
        befejezemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                befejezemButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("jó válaszok százalékban:");

        startButton.setText("Kezdés");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        ujListakeroGomb.setText("uj lista");
        ujListakeroGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ujListakeroGombActionPerformed(evt);
            }
        });

        jLabel5.setText("Jo válaszok megszakítás nélkül:");

        jLabel6.setText("Tesztek száma:");

        jLabel7.setText("80%");

        jLabel8.setText("90%");

        jLabel9.setText("100%");

        sz90tol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sz90tolActionPerformed(evt);
            }
        });

        jLabel10.setText("70%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(kovKerdesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ujListakeroGomb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(befejezemButton)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(startButton)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tesztekszamaField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(szazalekField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tippField, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                            .addComponent(helyesKodField))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(egymasUtanJoField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sz70tol))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(termeknevField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(mehetButton)
                                            .addGap(24, 24, 24)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sz80tol, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(sz90tol, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sz100, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(jLabel6)
                    .addComponent(tesztekszamaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(sz90tol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sz100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sz80tol, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(sz70tol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(termeknevField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tippField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mehetButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(helyesKodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(szazalekField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(egymasUtanJoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kovKerdesButton)
                    .addComponent(befejezemButton)
                    .addComponent(ujListakeroGomb))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void termeknevFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termeknevFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_termeknevFieldActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        randomtermek(termekekTesztre);
        termeknevField.setText(egytermeknev);

    }//GEN-LAST:event_startButtonActionPerformed

    private void tippFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tippFieldKeyPressed

    }//GEN-LAST:event_tippFieldKeyPressed

    private void tippFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tippFieldActionPerformed
      kodkiiras();


    }//GEN-LAST:event_tippFieldActionPerformed

    private void mehetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mehetButtonActionPerformed
        kodellenorzes();
    }//GEN-LAST:event_mehetButtonActionPerformed

    private void kovKerdesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kovKerdesButtonActionPerformed
        kodellenorzes();
        szazalekszamitas();
        if (szazalek >=70 && egymasutanjo >= 10) {
            ujlistkeszito();
        }

        
        randomtermek(termekekTesztre);
        termeknevField.setText(egytermeknev);
        tippField.setText("");
        helyesKodField.setText("");
    }//GEN-LAST:event_kovKerdesButtonActionPerformed

    private void ujListakeroGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ujListakeroGombActionPerformed
        szazalekszamitas();
        if (szazalek < 70 || egymasutanjo < 10) {
            JOptionPane.showMessageDialog(null, "Csak akkor léphetsz tovább ha a válaszaid legalább 70 % ban helyesek és most nyerő szériában legalább 10 kérdést válaszoltál meg.");
        } else {
            ujlistkeszito();
        }
    }//GEN-LAST:event_ujListakeroGombActionPerformed

    private void sz90tolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sz90tolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sz90tolActionPerformed

    private void befejezemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_befejezemButtonActionPerformed
       this.dispose();
    }//GEN-LAST:event_befejezemButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TesztInditas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TesztInditas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TesztInditas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TesztInditas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TesztInditas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton befejezemButton;
    private javax.swing.JTextField egymasUtanJoField;
    private javax.swing.JTextField helyesKodField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton kovKerdesButton;
    private javax.swing.JButton mehetButton;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField sz100;
    private javax.swing.JTextField sz70tol;
    private javax.swing.JTextField sz80tol;
    private javax.swing.JTextField sz90tol;
    private javax.swing.JTextField szazalekField;
    private javax.swing.JTextField termeknevField;
    private javax.swing.JTextField tesztekszamaField;
    private javax.swing.JTextField tippField;
    private javax.swing.JButton ujListakeroGomb;
    // End of variables declaration//GEN-END:variables
}
