/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plukodgyakorlo2;

import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Verosffy
 */
public class Vizsga extends javax.swing.JFrame {

    /**
     * Creates new form TesztBeallitas
     */
    ArrayList termekek = new ArrayList();
    ArrayList<TermekKodParos> tizeslista;
    String egytermekkod;
    String egytermeknev;
    int joValaszokSzama = 0;
    int sikertelenSz = 0;
    int sz70tolSz = 0;
    int sz80tolSz = 0;
    int sz90tolSz = 0;
    int sz100Sz = 0;
    int kerdesSorszama = 0;
    long starttime=System.nanoTime();
    long endtime=0;

    public Vizsga() {
        initComponents();
        population();
        eredmenykiiroFrissitese();

    }

    public void eredmenykiiroFrissitese() {
        sikertelenField.setText("" + sikertelenSz);
        sz70Field.setText("" + sz70tolSz);
        sz80Field.setText("" + sz80tolSz);
        sz90Field.setText("" + sz90tolSz);
        sz100Field.setText("" + sz100Sz);
    }

    public void population() {
        try {
            FileInputStream file = new FileInputStream("src\\segedlet\\TermekKodparos.dat");
            ObjectInputStream oInput = new ObjectInputStream(file);

            boolean endOfFile = false;//=ture

            try {
                while (!endOfFile) {//()endOfFile
                    termekek.add(oInput.readObject());
                }
            } catch (IOException ex) {
                endOfFile = true;//false
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public void tesztsorFeltolto(ArrayList<TermekKodParos> lista) {
        Random rd = new Random();
        tizeslista = new ArrayList<>();

        do {
            int vmi = rd.nextInt(termekek.size());

            if (tizeslista.isEmpty()
                    || !tizeslista.contains(lista.get(vmi))) {
                egytermeknev = lista.get(vmi).getTermeknev();
                egytermekkod = lista.get(vmi).getTermekkod();
                TermekKodParos uj = new TermekKodParos(egytermeknev, egytermekkod);
                tizeslista.add(uj);
                System.out.println(uj.getTermeknev() + uj.getTermekkod());

            }
        } while (tizeslista.size() < 10);
        for (int i = 0; i < tizeslista.size(); i++) {
            System.out.println(tizeslista.get(i).getTermeknev());
        }

    }

    public void kodellenorzoPontszamolo() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        startButton = new javax.swing.JButton();
        termeknevField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tippField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sikertelenField = new javax.swing.JTextField();
        sz70Field = new javax.swing.JTextField();
        sz80Field = new javax.swing.JTextField();
        sz90Field = new javax.swing.JTextField();
        sz100Field = new javax.swing.JTextField();
        ujtesztButton = new javax.swing.JButton();
        tesztadatoktorleseButton = new javax.swing.JButton();
        visszaButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        kerdessorszamField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        timeField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Egy vizsgasor mindössze tíz kérdésből áll. \nA vizsga sikeres amennyiben legalább 7 helyes választ születik.\n");
        jScrollPane1.setViewportView(jTextArea1);

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        termeknevField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termeknevFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("PLU kod:");

        tippField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tippFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Sikrtelen");

        jLabel3.setText("70%");

        jLabel4.setText("80%");

        jLabel5.setText("90%");

        jLabel6.setText("100%");

        sikertelenField.setText("jTextField1");
        sikertelenField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sikertelenFieldActionPerformed(evt);
            }
        });

        sz70Field.setText("jTextField2");

        sz80Field.setText("jTextField3");

        sz90Field.setText("jTextField4");

        sz100Field.setText("jTextField5");

        ujtesztButton.setText("Uj teszt");

        tesztadatoktorleseButton.setText("tesztadatok törlése");

        visszaButton.setText("Vissza");

        jLabel7.setText("kerdessorszám:");

        jLabel8.setText("ido:");

        timeField.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(termeknevField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sz100Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sz90Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sz80Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sz70Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sikertelenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ujtesztButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tesztadatoktorleseButton)
                            .addComponent(visszaButton))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tippField, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(startButton)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kerdessorszamField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(jLabel7)
                    .addComponent(kerdessorszamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(termeknevField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tippField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sikertelenField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ujtesztButton)
                    .addComponent(tesztadatoktorleseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sz70Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sz80Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(sz90Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(sz100Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(visszaButton)
                        .addGap(22, 22, 22))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
       long totaltime=System.nanoTime()-starttime;
       Date ido=new Date(totaltime/1000);
        tesztsorFeltolto(termekek);
        termeknevField.setText(tizeslista.get(kerdesSorszama).getTermeknev());
        starttime=System.nanoTime();
        timeField.setText(""+ido.toString());


    }//GEN-LAST:event_startButtonActionPerformed

    private void tippFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tippFieldActionPerformed
kerdessorszamField.setText(""+kerdesSorszama);
        String begepelt = tippField.getText();
        if (begepelt.equalsIgnoreCase(tizeslista.get(kerdesSorszama).getTermekkod())) {
            joValaszokSzama++;
        }
        kerdesSorszama++;
        if (kerdesSorszama ==10) {
            endtime=System.nanoTime();
            switch (joValaszokSzama) {
                case 10: {
                    sz100Sz++;
                    break;
                }
                case 9: {
                    sz90tolSz++;
                    break;
                }
                case 8: {
                    sz80tolSz++;
                    break;
                }
                case 7: {
                    sz70tolSz++;
                    break;
                }
                default:
                    sikertelenSz++;

                    break;
            }
            eredmenykiiroFrissitese();
            joValaszokSzama=0;
            kerdesSorszama=0;
            startButtonActionPerformed(evt);
            
 
        }
        else{
             termeknevField.setText(tizeslista.get(kerdesSorszama).getTermeknev());
        }tippField.setText("");
       
       
    }//GEN-LAST:event_tippFieldActionPerformed

    private void termeknevFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termeknevFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_termeknevFieldActionPerformed

    private void sikertelenFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sikertelenFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sikertelenFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vizsga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vizsga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vizsga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vizsga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vizsga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField kerdessorszamField;
    private javax.swing.JTextField sikertelenField;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField sz100Field;
    private javax.swing.JTextField sz70Field;
    private javax.swing.JTextField sz80Field;
    private javax.swing.JTextField sz90Field;
    private javax.swing.JTextField termeknevField;
    private javax.swing.JButton tesztadatoktorleseButton;
    private javax.swing.JTextField timeField;
    private javax.swing.JTextField tippField;
    private javax.swing.JButton ujtesztButton;
    private javax.swing.JButton visszaButton;
    // End of variables declaration//GEN-END:variables
}
